name: Feature Push

on:
  push:
    branches: [ feature ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test with Gradle and publish Pact verification results
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build test -Dpact.verifier.publishResults=true